# .github/workflows/ci.yml

name: Python Application CI

# このワークフローが実行されるタイミングを指定
on:
  push:
    branches: [ main, develop ] # mainかdevelopブランチにプッシュされた時
  pull_request:
    branches: [ main ] # mainブランチへのPull Requestが作成された時

jobs:
  build:
    runs-on: ubuntu-latest # 実行環境としてUbuntuの最新版を使用

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Pythonの環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # アプリケーションが使用するPythonバージョンを指定

      # 3. 依存ライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock # テスト用ライブラリもインストール

      # 4. pytestでテストを実行
      - name: Run tests with pytest
        run: |
          pytest